/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as SidenavLayoutRouteRouteImport } from './routes/sidenav-layout/route'
import { Route as SidenavLayoutIndexRouteImport } from './routes/sidenav-layout/index'
import { Route as SidenavLayoutPlayersPlayerIdRouteImport } from './routes/sidenav-layout/players/$playerId'
import { Route as BrawlhallaPlayersPlayerIdRouteRouteImport } from './routes/brawlhalla/players/$playerId/route'
import { Route as SidenavLayoutPlayersPlayerIdWeaponsRouteImport } from './routes/sidenav-layout/players/$playerId.weapons'
import { Route as SidenavLayoutPlayersPlayerIdLegendsRouteImport } from './routes/sidenav-layout/players/$playerId.legends'
import { Route as SidenavLayoutPlayersPlayerId2v2RouteImport } from './routes/sidenav-layout/players/$playerId.2v2'
import { Route as SidenavLayoutPlayersPlayerIdSplatRouteImport } from './routes/sidenav-layout/players/$playerId.$'
import { Route as BrawlhallaPlayersPlayerId2v2RouteImport } from './routes/brawlhalla/players/$playerId/2v2'
import { Route as BrawlhallaPlayersPlayerIdSplatRouteImport } from './routes/brawlhalla/players/$playerId/$'

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const SidenavLayoutRouteRoute = SidenavLayoutRouteRouteImport.update({
  id: '/sidenav-layout',
  path: '/sidenav-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SidenavLayoutIndexRoute = SidenavLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidenavLayoutRouteRoute,
} as any)
const SidenavLayoutPlayersPlayerIdRoute =
  SidenavLayoutPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => SidenavLayoutRouteRoute,
  } as any)
const BrawlhallaPlayersPlayerIdRouteRoute =
  BrawlhallaPlayersPlayerIdRouteRouteImport.update({
    id: '/brawlhalla/players/$playerId',
    path: '/brawlhalla/players/$playerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SidenavLayoutPlayersPlayerIdWeaponsRoute =
  SidenavLayoutPlayersPlayerIdWeaponsRouteImport.update({
    id: '/weapons',
    path: '/weapons',
    getParentRoute: () => SidenavLayoutPlayersPlayerIdRoute,
  } as any)
const SidenavLayoutPlayersPlayerIdLegendsRoute =
  SidenavLayoutPlayersPlayerIdLegendsRouteImport.update({
    id: '/legends',
    path: '/legends',
    getParentRoute: () => SidenavLayoutPlayersPlayerIdRoute,
  } as any)
const SidenavLayoutPlayersPlayerId2v2Route =
  SidenavLayoutPlayersPlayerId2v2RouteImport.update({
    id: '/2v2',
    path: '/2v2',
    getParentRoute: () => SidenavLayoutPlayersPlayerIdRoute,
  } as any)
const SidenavLayoutPlayersPlayerIdSplatRoute =
  SidenavLayoutPlayersPlayerIdSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => SidenavLayoutPlayersPlayerIdRoute,
  } as any)
const BrawlhallaPlayersPlayerId2v2Route =
  BrawlhallaPlayersPlayerId2v2RouteImport.update({
    id: '/2v2',
    path: '/2v2',
    getParentRoute: () => BrawlhallaPlayersPlayerIdRouteRoute,
  } as any)
const BrawlhallaPlayersPlayerIdSplatRoute =
  BrawlhallaPlayersPlayerIdSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => BrawlhallaPlayersPlayerIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sidenav-layout': typeof SidenavLayoutRouteRouteWithChildren
  '/ui': typeof UiRoute
  '/sidenav-layout/': typeof SidenavLayoutIndexRoute
  '/brawlhalla/players/$playerId': typeof BrawlhallaPlayersPlayerIdRouteRouteWithChildren
  '/sidenav-layout/players/$playerId': typeof SidenavLayoutPlayersPlayerIdRouteWithChildren
  '/brawlhalla/players/$playerId/$': typeof BrawlhallaPlayersPlayerIdSplatRoute
  '/brawlhalla/players/$playerId/2v2': typeof BrawlhallaPlayersPlayerId2v2Route
  '/sidenav-layout/players/$playerId/$': typeof SidenavLayoutPlayersPlayerIdSplatRoute
  '/sidenav-layout/players/$playerId/2v2': typeof SidenavLayoutPlayersPlayerId2v2Route
  '/sidenav-layout/players/$playerId/legends': typeof SidenavLayoutPlayersPlayerIdLegendsRoute
  '/sidenav-layout/players/$playerId/weapons': typeof SidenavLayoutPlayersPlayerIdWeaponsRoute
}
export interface FileRoutesByTo {
  '/ui': typeof UiRoute
  '/sidenav-layout': typeof SidenavLayoutIndexRoute
  '/brawlhalla/players/$playerId': typeof BrawlhallaPlayersPlayerIdRouteRouteWithChildren
  '/sidenav-layout/players/$playerId': typeof SidenavLayoutPlayersPlayerIdRouteWithChildren
  '/brawlhalla/players/$playerId/$': typeof BrawlhallaPlayersPlayerIdSplatRoute
  '/brawlhalla/players/$playerId/2v2': typeof BrawlhallaPlayersPlayerId2v2Route
  '/sidenav-layout/players/$playerId/$': typeof SidenavLayoutPlayersPlayerIdSplatRoute
  '/sidenav-layout/players/$playerId/2v2': typeof SidenavLayoutPlayersPlayerId2v2Route
  '/sidenav-layout/players/$playerId/legends': typeof SidenavLayoutPlayersPlayerIdLegendsRoute
  '/sidenav-layout/players/$playerId/weapons': typeof SidenavLayoutPlayersPlayerIdWeaponsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sidenav-layout': typeof SidenavLayoutRouteRouteWithChildren
  '/ui': typeof UiRoute
  '/sidenav-layout/': typeof SidenavLayoutIndexRoute
  '/brawlhalla/players/$playerId': typeof BrawlhallaPlayersPlayerIdRouteRouteWithChildren
  '/sidenav-layout/players/$playerId': typeof SidenavLayoutPlayersPlayerIdRouteWithChildren
  '/brawlhalla/players/$playerId/$': typeof BrawlhallaPlayersPlayerIdSplatRoute
  '/brawlhalla/players/$playerId/2v2': typeof BrawlhallaPlayersPlayerId2v2Route
  '/sidenav-layout/players/$playerId/$': typeof SidenavLayoutPlayersPlayerIdSplatRoute
  '/sidenav-layout/players/$playerId/2v2': typeof SidenavLayoutPlayersPlayerId2v2Route
  '/sidenav-layout/players/$playerId/legends': typeof SidenavLayoutPlayersPlayerIdLegendsRoute
  '/sidenav-layout/players/$playerId/weapons': typeof SidenavLayoutPlayersPlayerIdWeaponsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sidenav-layout'
    | '/ui'
    | '/sidenav-layout/'
    | '/brawlhalla/players/$playerId'
    | '/sidenav-layout/players/$playerId'
    | '/brawlhalla/players/$playerId/$'
    | '/brawlhalla/players/$playerId/2v2'
    | '/sidenav-layout/players/$playerId/$'
    | '/sidenav-layout/players/$playerId/2v2'
    | '/sidenav-layout/players/$playerId/legends'
    | '/sidenav-layout/players/$playerId/weapons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ui'
    | '/sidenav-layout'
    | '/brawlhalla/players/$playerId'
    | '/sidenav-layout/players/$playerId'
    | '/brawlhalla/players/$playerId/$'
    | '/brawlhalla/players/$playerId/2v2'
    | '/sidenav-layout/players/$playerId/$'
    | '/sidenav-layout/players/$playerId/2v2'
    | '/sidenav-layout/players/$playerId/legends'
    | '/sidenav-layout/players/$playerId/weapons'
  id:
    | '__root__'
    | '/sidenav-layout'
    | '/ui'
    | '/sidenav-layout/'
    | '/brawlhalla/players/$playerId'
    | '/sidenav-layout/players/$playerId'
    | '/brawlhalla/players/$playerId/$'
    | '/brawlhalla/players/$playerId/2v2'
    | '/sidenav-layout/players/$playerId/$'
    | '/sidenav-layout/players/$playerId/2v2'
    | '/sidenav-layout/players/$playerId/legends'
    | '/sidenav-layout/players/$playerId/weapons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidenavLayoutRouteRoute: typeof SidenavLayoutRouteRouteWithChildren
  UiRoute: typeof UiRoute
  BrawlhallaPlayersPlayerIdRouteRoute: typeof BrawlhallaPlayersPlayerIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidenav-layout': {
      id: '/sidenav-layout'
      path: '/sidenav-layout'
      fullPath: '/sidenav-layout'
      preLoaderRoute: typeof SidenavLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidenav-layout/': {
      id: '/sidenav-layout/'
      path: '/'
      fullPath: '/sidenav-layout/'
      preLoaderRoute: typeof SidenavLayoutIndexRouteImport
      parentRoute: typeof SidenavLayoutRouteRoute
    }
    '/sidenav-layout/players/$playerId': {
      id: '/sidenav-layout/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/sidenav-layout/players/$playerId'
      preLoaderRoute: typeof SidenavLayoutPlayersPlayerIdRouteImport
      parentRoute: typeof SidenavLayoutRouteRoute
    }
    '/brawlhalla/players/$playerId': {
      id: '/brawlhalla/players/$playerId'
      path: '/brawlhalla/players/$playerId'
      fullPath: '/brawlhalla/players/$playerId'
      preLoaderRoute: typeof BrawlhallaPlayersPlayerIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidenav-layout/players/$playerId/weapons': {
      id: '/sidenav-layout/players/$playerId/weapons'
      path: '/weapons'
      fullPath: '/sidenav-layout/players/$playerId/weapons'
      preLoaderRoute: typeof SidenavLayoutPlayersPlayerIdWeaponsRouteImport
      parentRoute: typeof SidenavLayoutPlayersPlayerIdRoute
    }
    '/sidenav-layout/players/$playerId/legends': {
      id: '/sidenav-layout/players/$playerId/legends'
      path: '/legends'
      fullPath: '/sidenav-layout/players/$playerId/legends'
      preLoaderRoute: typeof SidenavLayoutPlayersPlayerIdLegendsRouteImport
      parentRoute: typeof SidenavLayoutPlayersPlayerIdRoute
    }
    '/sidenav-layout/players/$playerId/2v2': {
      id: '/sidenav-layout/players/$playerId/2v2'
      path: '/2v2'
      fullPath: '/sidenav-layout/players/$playerId/2v2'
      preLoaderRoute: typeof SidenavLayoutPlayersPlayerId2v2RouteImport
      parentRoute: typeof SidenavLayoutPlayersPlayerIdRoute
    }
    '/sidenav-layout/players/$playerId/$': {
      id: '/sidenav-layout/players/$playerId/$'
      path: '/$'
      fullPath: '/sidenav-layout/players/$playerId/$'
      preLoaderRoute: typeof SidenavLayoutPlayersPlayerIdSplatRouteImport
      parentRoute: typeof SidenavLayoutPlayersPlayerIdRoute
    }
    '/brawlhalla/players/$playerId/2v2': {
      id: '/brawlhalla/players/$playerId/2v2'
      path: '/2v2'
      fullPath: '/brawlhalla/players/$playerId/2v2'
      preLoaderRoute: typeof BrawlhallaPlayersPlayerId2v2RouteImport
      parentRoute: typeof BrawlhallaPlayersPlayerIdRouteRoute
    }
    '/brawlhalla/players/$playerId/$': {
      id: '/brawlhalla/players/$playerId/$'
      path: '/$'
      fullPath: '/brawlhalla/players/$playerId/$'
      preLoaderRoute: typeof BrawlhallaPlayersPlayerIdSplatRouteImport
      parentRoute: typeof BrawlhallaPlayersPlayerIdRouteRoute
    }
  }
}

interface SidenavLayoutPlayersPlayerIdRouteChildren {
  SidenavLayoutPlayersPlayerIdSplatRoute: typeof SidenavLayoutPlayersPlayerIdSplatRoute
  SidenavLayoutPlayersPlayerId2v2Route: typeof SidenavLayoutPlayersPlayerId2v2Route
  SidenavLayoutPlayersPlayerIdLegendsRoute: typeof SidenavLayoutPlayersPlayerIdLegendsRoute
  SidenavLayoutPlayersPlayerIdWeaponsRoute: typeof SidenavLayoutPlayersPlayerIdWeaponsRoute
}

const SidenavLayoutPlayersPlayerIdRouteChildren: SidenavLayoutPlayersPlayerIdRouteChildren =
  {
    SidenavLayoutPlayersPlayerIdSplatRoute:
      SidenavLayoutPlayersPlayerIdSplatRoute,
    SidenavLayoutPlayersPlayerId2v2Route: SidenavLayoutPlayersPlayerId2v2Route,
    SidenavLayoutPlayersPlayerIdLegendsRoute:
      SidenavLayoutPlayersPlayerIdLegendsRoute,
    SidenavLayoutPlayersPlayerIdWeaponsRoute:
      SidenavLayoutPlayersPlayerIdWeaponsRoute,
  }

const SidenavLayoutPlayersPlayerIdRouteWithChildren =
  SidenavLayoutPlayersPlayerIdRoute._addFileChildren(
    SidenavLayoutPlayersPlayerIdRouteChildren,
  )

interface SidenavLayoutRouteRouteChildren {
  SidenavLayoutIndexRoute: typeof SidenavLayoutIndexRoute
  SidenavLayoutPlayersPlayerIdRoute: typeof SidenavLayoutPlayersPlayerIdRouteWithChildren
}

const SidenavLayoutRouteRouteChildren: SidenavLayoutRouteRouteChildren = {
  SidenavLayoutIndexRoute: SidenavLayoutIndexRoute,
  SidenavLayoutPlayersPlayerIdRoute:
    SidenavLayoutPlayersPlayerIdRouteWithChildren,
}

const SidenavLayoutRouteRouteWithChildren =
  SidenavLayoutRouteRoute._addFileChildren(SidenavLayoutRouteRouteChildren)

interface BrawlhallaPlayersPlayerIdRouteRouteChildren {
  BrawlhallaPlayersPlayerIdSplatRoute: typeof BrawlhallaPlayersPlayerIdSplatRoute
  BrawlhallaPlayersPlayerId2v2Route: typeof BrawlhallaPlayersPlayerId2v2Route
}

const BrawlhallaPlayersPlayerIdRouteRouteChildren: BrawlhallaPlayersPlayerIdRouteRouteChildren =
  {
    BrawlhallaPlayersPlayerIdSplatRoute: BrawlhallaPlayersPlayerIdSplatRoute,
    BrawlhallaPlayersPlayerId2v2Route: BrawlhallaPlayersPlayerId2v2Route,
  }

const BrawlhallaPlayersPlayerIdRouteRouteWithChildren =
  BrawlhallaPlayersPlayerIdRouteRoute._addFileChildren(
    BrawlhallaPlayersPlayerIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  SidenavLayoutRouteRoute: SidenavLayoutRouteRouteWithChildren,
  UiRoute: UiRoute,
  BrawlhallaPlayersPlayerIdRouteRoute:
    BrawlhallaPlayersPlayerIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
