/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as SidenavLayoutRouteRouteImport } from './routes/sidenav-layout/route'
import { Route as SidenavRouteRouteImport } from './routes/_sidenav/route'
import { Route as SidenavLayoutIndexRouteImport } from './routes/sidenav-layout/index'
import { Route as SidenavIndexRouteImport } from './routes/_sidenav/index'
import { Route as SidenavLayoutPlayersPlayerIdRouteImport } from './routes/sidenav-layout/players/$playerId'
import { Route as SidenavLayoutPlayersPlayerIdWeaponsRouteImport } from './routes/sidenav-layout/players/$playerId.weapons'
import { Route as SidenavLayoutPlayersPlayerIdLegendsRouteImport } from './routes/sidenav-layout/players/$playerId.legends'
import { Route as SidenavLayoutPlayersPlayerId2v2RouteImport } from './routes/sidenav-layout/players/$playerId.2v2'
import { Route as SidenavLayoutPlayersPlayerIdSplatRouteImport } from './routes/sidenav-layout/players/$playerId.$'
import { Route as SidenavBrawlhallaPlayersPlayerIdRouteRouteImport } from './routes/_sidenav/brawlhalla/players/$playerId/route'
import { Route as SidenavBrawlhallaPlayersPlayerId2v2RouteImport } from './routes/_sidenav/brawlhalla/players/$playerId/2v2'
import { Route as SidenavBrawlhallaPlayersPlayerIdSplatRouteImport } from './routes/_sidenav/brawlhalla/players/$playerId/$'

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const SidenavLayoutRouteRoute = SidenavLayoutRouteRouteImport.update({
  id: '/sidenav-layout',
  path: '/sidenav-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SidenavRouteRoute = SidenavRouteRouteImport.update({
  id: '/_sidenav',
  getParentRoute: () => rootRouteImport,
} as any)
const SidenavLayoutIndexRoute = SidenavLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidenavLayoutRouteRoute,
} as any)
const SidenavIndexRoute = SidenavIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidenavRouteRoute,
} as any)
const SidenavLayoutPlayersPlayerIdRoute =
  SidenavLayoutPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => SidenavLayoutRouteRoute,
  } as any)
const SidenavLayoutPlayersPlayerIdWeaponsRoute =
  SidenavLayoutPlayersPlayerIdWeaponsRouteImport.update({
    id: '/weapons',
    path: '/weapons',
    getParentRoute: () => SidenavLayoutPlayersPlayerIdRoute,
  } as any)
const SidenavLayoutPlayersPlayerIdLegendsRoute =
  SidenavLayoutPlayersPlayerIdLegendsRouteImport.update({
    id: '/legends',
    path: '/legends',
    getParentRoute: () => SidenavLayoutPlayersPlayerIdRoute,
  } as any)
const SidenavLayoutPlayersPlayerId2v2Route =
  SidenavLayoutPlayersPlayerId2v2RouteImport.update({
    id: '/2v2',
    path: '/2v2',
    getParentRoute: () => SidenavLayoutPlayersPlayerIdRoute,
  } as any)
const SidenavLayoutPlayersPlayerIdSplatRoute =
  SidenavLayoutPlayersPlayerIdSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => SidenavLayoutPlayersPlayerIdRoute,
  } as any)
const SidenavBrawlhallaPlayersPlayerIdRouteRoute =
  SidenavBrawlhallaPlayersPlayerIdRouteRouteImport.update({
    id: '/brawlhalla/players/$playerId',
    path: '/brawlhalla/players/$playerId',
    getParentRoute: () => SidenavRouteRoute,
  } as any)
const SidenavBrawlhallaPlayersPlayerId2v2Route =
  SidenavBrawlhallaPlayersPlayerId2v2RouteImport.update({
    id: '/2v2',
    path: '/2v2',
    getParentRoute: () => SidenavBrawlhallaPlayersPlayerIdRouteRoute,
  } as any)
const SidenavBrawlhallaPlayersPlayerIdSplatRoute =
  SidenavBrawlhallaPlayersPlayerIdSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => SidenavBrawlhallaPlayersPlayerIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sidenav-layout': typeof SidenavLayoutRouteRouteWithChildren
  '/ui': typeof UiRoute
  '/': typeof SidenavIndexRoute
  '/sidenav-layout/': typeof SidenavLayoutIndexRoute
  '/sidenav-layout/players/$playerId': typeof SidenavLayoutPlayersPlayerIdRouteWithChildren
  '/brawlhalla/players/$playerId': typeof SidenavBrawlhallaPlayersPlayerIdRouteRouteWithChildren
  '/sidenav-layout/players/$playerId/$': typeof SidenavLayoutPlayersPlayerIdSplatRoute
  '/sidenav-layout/players/$playerId/2v2': typeof SidenavLayoutPlayersPlayerId2v2Route
  '/sidenav-layout/players/$playerId/legends': typeof SidenavLayoutPlayersPlayerIdLegendsRoute
  '/sidenav-layout/players/$playerId/weapons': typeof SidenavLayoutPlayersPlayerIdWeaponsRoute
  '/brawlhalla/players/$playerId/$': typeof SidenavBrawlhallaPlayersPlayerIdSplatRoute
  '/brawlhalla/players/$playerId/2v2': typeof SidenavBrawlhallaPlayersPlayerId2v2Route
}
export interface FileRoutesByTo {
  '/ui': typeof UiRoute
  '/': typeof SidenavIndexRoute
  '/sidenav-layout': typeof SidenavLayoutIndexRoute
  '/sidenav-layout/players/$playerId': typeof SidenavLayoutPlayersPlayerIdRouteWithChildren
  '/brawlhalla/players/$playerId': typeof SidenavBrawlhallaPlayersPlayerIdRouteRouteWithChildren
  '/sidenav-layout/players/$playerId/$': typeof SidenavLayoutPlayersPlayerIdSplatRoute
  '/sidenav-layout/players/$playerId/2v2': typeof SidenavLayoutPlayersPlayerId2v2Route
  '/sidenav-layout/players/$playerId/legends': typeof SidenavLayoutPlayersPlayerIdLegendsRoute
  '/sidenav-layout/players/$playerId/weapons': typeof SidenavLayoutPlayersPlayerIdWeaponsRoute
  '/brawlhalla/players/$playerId/$': typeof SidenavBrawlhallaPlayersPlayerIdSplatRoute
  '/brawlhalla/players/$playerId/2v2': typeof SidenavBrawlhallaPlayersPlayerId2v2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidenav': typeof SidenavRouteRouteWithChildren
  '/sidenav-layout': typeof SidenavLayoutRouteRouteWithChildren
  '/ui': typeof UiRoute
  '/_sidenav/': typeof SidenavIndexRoute
  '/sidenav-layout/': typeof SidenavLayoutIndexRoute
  '/sidenav-layout/players/$playerId': typeof SidenavLayoutPlayersPlayerIdRouteWithChildren
  '/_sidenav/brawlhalla/players/$playerId': typeof SidenavBrawlhallaPlayersPlayerIdRouteRouteWithChildren
  '/sidenav-layout/players/$playerId/$': typeof SidenavLayoutPlayersPlayerIdSplatRoute
  '/sidenav-layout/players/$playerId/2v2': typeof SidenavLayoutPlayersPlayerId2v2Route
  '/sidenav-layout/players/$playerId/legends': typeof SidenavLayoutPlayersPlayerIdLegendsRoute
  '/sidenav-layout/players/$playerId/weapons': typeof SidenavLayoutPlayersPlayerIdWeaponsRoute
  '/_sidenav/brawlhalla/players/$playerId/$': typeof SidenavBrawlhallaPlayersPlayerIdSplatRoute
  '/_sidenav/brawlhalla/players/$playerId/2v2': typeof SidenavBrawlhallaPlayersPlayerId2v2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sidenav-layout'
    | '/ui'
    | '/'
    | '/sidenav-layout/'
    | '/sidenav-layout/players/$playerId'
    | '/brawlhalla/players/$playerId'
    | '/sidenav-layout/players/$playerId/$'
    | '/sidenav-layout/players/$playerId/2v2'
    | '/sidenav-layout/players/$playerId/legends'
    | '/sidenav-layout/players/$playerId/weapons'
    | '/brawlhalla/players/$playerId/$'
    | '/brawlhalla/players/$playerId/2v2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ui'
    | '/'
    | '/sidenav-layout'
    | '/sidenav-layout/players/$playerId'
    | '/brawlhalla/players/$playerId'
    | '/sidenav-layout/players/$playerId/$'
    | '/sidenav-layout/players/$playerId/2v2'
    | '/sidenav-layout/players/$playerId/legends'
    | '/sidenav-layout/players/$playerId/weapons'
    | '/brawlhalla/players/$playerId/$'
    | '/brawlhalla/players/$playerId/2v2'
  id:
    | '__root__'
    | '/_sidenav'
    | '/sidenav-layout'
    | '/ui'
    | '/_sidenav/'
    | '/sidenav-layout/'
    | '/sidenav-layout/players/$playerId'
    | '/_sidenav/brawlhalla/players/$playerId'
    | '/sidenav-layout/players/$playerId/$'
    | '/sidenav-layout/players/$playerId/2v2'
    | '/sidenav-layout/players/$playerId/legends'
    | '/sidenav-layout/players/$playerId/weapons'
    | '/_sidenav/brawlhalla/players/$playerId/$'
    | '/_sidenav/brawlhalla/players/$playerId/2v2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidenavRouteRoute: typeof SidenavRouteRouteWithChildren
  SidenavLayoutRouteRoute: typeof SidenavLayoutRouteRouteWithChildren
  UiRoute: typeof UiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidenav-layout': {
      id: '/sidenav-layout'
      path: '/sidenav-layout'
      fullPath: '/sidenav-layout'
      preLoaderRoute: typeof SidenavLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidenav': {
      id: '/_sidenav'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidenavRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidenav-layout/': {
      id: '/sidenav-layout/'
      path: '/'
      fullPath: '/sidenav-layout/'
      preLoaderRoute: typeof SidenavLayoutIndexRouteImport
      parentRoute: typeof SidenavLayoutRouteRoute
    }
    '/_sidenav/': {
      id: '/_sidenav/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidenavIndexRouteImport
      parentRoute: typeof SidenavRouteRoute
    }
    '/sidenav-layout/players/$playerId': {
      id: '/sidenav-layout/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/sidenav-layout/players/$playerId'
      preLoaderRoute: typeof SidenavLayoutPlayersPlayerIdRouteImport
      parentRoute: typeof SidenavLayoutRouteRoute
    }
    '/sidenav-layout/players/$playerId/weapons': {
      id: '/sidenav-layout/players/$playerId/weapons'
      path: '/weapons'
      fullPath: '/sidenav-layout/players/$playerId/weapons'
      preLoaderRoute: typeof SidenavLayoutPlayersPlayerIdWeaponsRouteImport
      parentRoute: typeof SidenavLayoutPlayersPlayerIdRoute
    }
    '/sidenav-layout/players/$playerId/legends': {
      id: '/sidenav-layout/players/$playerId/legends'
      path: '/legends'
      fullPath: '/sidenav-layout/players/$playerId/legends'
      preLoaderRoute: typeof SidenavLayoutPlayersPlayerIdLegendsRouteImport
      parentRoute: typeof SidenavLayoutPlayersPlayerIdRoute
    }
    '/sidenav-layout/players/$playerId/2v2': {
      id: '/sidenav-layout/players/$playerId/2v2'
      path: '/2v2'
      fullPath: '/sidenav-layout/players/$playerId/2v2'
      preLoaderRoute: typeof SidenavLayoutPlayersPlayerId2v2RouteImport
      parentRoute: typeof SidenavLayoutPlayersPlayerIdRoute
    }
    '/sidenav-layout/players/$playerId/$': {
      id: '/sidenav-layout/players/$playerId/$'
      path: '/$'
      fullPath: '/sidenav-layout/players/$playerId/$'
      preLoaderRoute: typeof SidenavLayoutPlayersPlayerIdSplatRouteImport
      parentRoute: typeof SidenavLayoutPlayersPlayerIdRoute
    }
    '/_sidenav/brawlhalla/players/$playerId': {
      id: '/_sidenav/brawlhalla/players/$playerId'
      path: '/brawlhalla/players/$playerId'
      fullPath: '/brawlhalla/players/$playerId'
      preLoaderRoute: typeof SidenavBrawlhallaPlayersPlayerIdRouteRouteImport
      parentRoute: typeof SidenavRouteRoute
    }
    '/_sidenav/brawlhalla/players/$playerId/2v2': {
      id: '/_sidenav/brawlhalla/players/$playerId/2v2'
      path: '/2v2'
      fullPath: '/brawlhalla/players/$playerId/2v2'
      preLoaderRoute: typeof SidenavBrawlhallaPlayersPlayerId2v2RouteImport
      parentRoute: typeof SidenavBrawlhallaPlayersPlayerIdRouteRoute
    }
    '/_sidenav/brawlhalla/players/$playerId/$': {
      id: '/_sidenav/brawlhalla/players/$playerId/$'
      path: '/$'
      fullPath: '/brawlhalla/players/$playerId/$'
      preLoaderRoute: typeof SidenavBrawlhallaPlayersPlayerIdSplatRouteImport
      parentRoute: typeof SidenavBrawlhallaPlayersPlayerIdRouteRoute
    }
  }
}

interface SidenavBrawlhallaPlayersPlayerIdRouteRouteChildren {
  SidenavBrawlhallaPlayersPlayerIdSplatRoute: typeof SidenavBrawlhallaPlayersPlayerIdSplatRoute
  SidenavBrawlhallaPlayersPlayerId2v2Route: typeof SidenavBrawlhallaPlayersPlayerId2v2Route
}

const SidenavBrawlhallaPlayersPlayerIdRouteRouteChildren: SidenavBrawlhallaPlayersPlayerIdRouteRouteChildren =
  {
    SidenavBrawlhallaPlayersPlayerIdSplatRoute:
      SidenavBrawlhallaPlayersPlayerIdSplatRoute,
    SidenavBrawlhallaPlayersPlayerId2v2Route:
      SidenavBrawlhallaPlayersPlayerId2v2Route,
  }

const SidenavBrawlhallaPlayersPlayerIdRouteRouteWithChildren =
  SidenavBrawlhallaPlayersPlayerIdRouteRoute._addFileChildren(
    SidenavBrawlhallaPlayersPlayerIdRouteRouteChildren,
  )

interface SidenavRouteRouteChildren {
  SidenavIndexRoute: typeof SidenavIndexRoute
  SidenavBrawlhallaPlayersPlayerIdRouteRoute: typeof SidenavBrawlhallaPlayersPlayerIdRouteRouteWithChildren
}

const SidenavRouteRouteChildren: SidenavRouteRouteChildren = {
  SidenavIndexRoute: SidenavIndexRoute,
  SidenavBrawlhallaPlayersPlayerIdRouteRoute:
    SidenavBrawlhallaPlayersPlayerIdRouteRouteWithChildren,
}

const SidenavRouteRouteWithChildren = SidenavRouteRoute._addFileChildren(
  SidenavRouteRouteChildren,
)

interface SidenavLayoutPlayersPlayerIdRouteChildren {
  SidenavLayoutPlayersPlayerIdSplatRoute: typeof SidenavLayoutPlayersPlayerIdSplatRoute
  SidenavLayoutPlayersPlayerId2v2Route: typeof SidenavLayoutPlayersPlayerId2v2Route
  SidenavLayoutPlayersPlayerIdLegendsRoute: typeof SidenavLayoutPlayersPlayerIdLegendsRoute
  SidenavLayoutPlayersPlayerIdWeaponsRoute: typeof SidenavLayoutPlayersPlayerIdWeaponsRoute
}

const SidenavLayoutPlayersPlayerIdRouteChildren: SidenavLayoutPlayersPlayerIdRouteChildren =
  {
    SidenavLayoutPlayersPlayerIdSplatRoute:
      SidenavLayoutPlayersPlayerIdSplatRoute,
    SidenavLayoutPlayersPlayerId2v2Route: SidenavLayoutPlayersPlayerId2v2Route,
    SidenavLayoutPlayersPlayerIdLegendsRoute:
      SidenavLayoutPlayersPlayerIdLegendsRoute,
    SidenavLayoutPlayersPlayerIdWeaponsRoute:
      SidenavLayoutPlayersPlayerIdWeaponsRoute,
  }

const SidenavLayoutPlayersPlayerIdRouteWithChildren =
  SidenavLayoutPlayersPlayerIdRoute._addFileChildren(
    SidenavLayoutPlayersPlayerIdRouteChildren,
  )

interface SidenavLayoutRouteRouteChildren {
  SidenavLayoutIndexRoute: typeof SidenavLayoutIndexRoute
  SidenavLayoutPlayersPlayerIdRoute: typeof SidenavLayoutPlayersPlayerIdRouteWithChildren
}

const SidenavLayoutRouteRouteChildren: SidenavLayoutRouteRouteChildren = {
  SidenavLayoutIndexRoute: SidenavLayoutIndexRoute,
  SidenavLayoutPlayersPlayerIdRoute:
    SidenavLayoutPlayersPlayerIdRouteWithChildren,
}

const SidenavLayoutRouteRouteWithChildren =
  SidenavLayoutRouteRoute._addFileChildren(SidenavLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SidenavRouteRoute: SidenavRouteRouteWithChildren,
  SidenavLayoutRouteRoute: SidenavLayoutRouteRouteWithChildren,
  UiRoute: UiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
