include:
  - path: ./apps/instrumentation/compose.yml

services:
  postgres:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dair
      POSTGRES_PASSWORD: dair
      POSTGRES_DB: dair
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dair -d dair"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./.data:/var/lib/postgresql/18/docker

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data

volumes:
  redis-data:
