services:
  postgres:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dair
      POSTGRES_PASSWORD: dair
      POSTGRES_DB: dair
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dair -d dair"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./.data:/var/lib/postgresql/18/docker

  # Grafana Alloy - OpenTelemetry Collector
  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345" # Alloy UI
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    volumes:
      - ./apps/monitoring/alloy/config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy/data
    depends_on:
      loki:
        condition: service_healthy
      tempo:
        condition: service_started

  # Grafana Loki - Log Aggregation
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    volumes:
      - ./apps/monitoring/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Grafana Tempo - Distributed Tracing
  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200" # Tempo HTTP
      - "9095:9095" # Tempo gRPC
    volumes:
      - ./apps/monitoring/tempo/tempo-config.yaml:/etc/tempo/config.yaml
      - tempo-data:/var/tempo
    command: -config.file=/etc/tempo/config.yaml

  # Grafana - Visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=correcthorsebatterystaple
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=info
    volumes:
      - ./apps/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      loki:
        condition: service_healthy
      tempo:
        condition: service_started

volumes:
  alloy-data:
  loki-data:
  tempo-data:
  grafana-data:
