ARG VARIANT=latest
FROM oven/bun:${VARIANT}
WORKDIR /usr/local/app

# Use bash to be able to source files
SHELL ["/bin/bash", "-c"]

# Install dependencies
RUN apt-get update \
    && apt-get install -y curl \
    && apt-get -y autoclean

# Environment variables
ENV NVM_DIR /usr/local/nvm
ENV NVM_VERSION 0.40.1
ENV NODE_VERSION 20.18.0

# Install NVM and Node (Needed for drizzle: https://github.com/oven-sh/bun/issues/7343)
RUN mkdir -p ${NVM_DIR} \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | bash \
    && source ${NVM_DIR}/nvm.sh \
    && nvm install ${NODE_VERSION} \
    && nvm alias default ${NODE_VERSION}

# Add node to path
ENV NODE_PATH ${NVM_DIR}/versions/node/v${NODE_VERSION}/lib/node_modules
ENV PATH ${NVM_DIR}/versions/node/v${NODE_VERSION}/bin:$PATH

RUN node --version

COPY ./package.json ./bun.lockb ./
RUN bun install --frozen-lockfile

CMD ["bun", "run", "front:dev"]
