/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125SidebarLayoutRouteRouteImport } from './routes/{-$locale}/_sidebar-layout/route'
import { Route as Char123LocaleChar125SidebarLayoutIndexRouteImport } from './routes/{-$locale}/_sidebar-layout/index'
import { Route as Char123LocaleChar125SidebarLayoutBrawlhallaPlayersPlayerIdChar123TabChar125RouteRouteImport } from './routes/{-$locale}/_sidebar-layout/brawlhalla/players/$playerId/{-$tab}/route'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SidebarLayoutRouteRoute =
  Char123LocaleChar125SidebarLayoutRouteRouteImport.update({
    id: '/_sidebar-layout',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SidebarLayoutIndexRoute =
  Char123LocaleChar125SidebarLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125SidebarLayoutRouteRoute,
  } as any)
const Char123LocaleChar125SidebarLayoutBrawlhallaPlayersPlayerIdChar123TabChar125RouteRoute =
  Char123LocaleChar125SidebarLayoutBrawlhallaPlayersPlayerIdChar123TabChar125RouteRouteImport.update(
    {
      id: '/brawlhalla/players/$playerId/{-$tab}',
      path: '/brawlhalla/players/$playerId/{-$tab}',
      getParentRoute: () => Char123LocaleChar125SidebarLayoutRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125SidebarLayoutRouteRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125SidebarLayoutIndexRoute
  '/{-$locale}/brawlhalla/players/$playerId/{-$tab}': typeof Char123LocaleChar125SidebarLayoutBrawlhallaPlayersPlayerIdChar123TabChar125RouteRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125SidebarLayoutIndexRoute
  '/{-$locale}/brawlhalla/players/$playerId/{-$tab}': typeof Char123LocaleChar125SidebarLayoutBrawlhallaPlayersPlayerIdChar123TabChar125RouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/_sidebar-layout': typeof Char123LocaleChar125SidebarLayoutRouteRouteWithChildren
  '/{-$locale}/_sidebar-layout/': typeof Char123LocaleChar125SidebarLayoutIndexRoute
  '/{-$locale}/_sidebar-layout/brawlhalla/players/$playerId/{-$tab}': typeof Char123LocaleChar125SidebarLayoutBrawlhallaPlayersPlayerIdChar123TabChar125RouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/brawlhalla/players/$playerId/{-$tab}'
  fileRoutesByTo: FileRoutesByTo
  to: '/{-$locale}' | '/{-$locale}/brawlhalla/players/$playerId/{-$tab}'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/_sidebar-layout'
    | '/{-$locale}/_sidebar-layout/'
    | '/{-$locale}/_sidebar-layout/brawlhalla/players/$playerId/{-$tab}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_sidebar-layout': {
      id: '/{-$locale}/_sidebar-layout'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125SidebarLayoutRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_sidebar-layout/': {
      id: '/{-$locale}/_sidebar-layout/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125SidebarLayoutIndexRouteImport
      parentRoute: typeof Char123LocaleChar125SidebarLayoutRouteRoute
    }
    '/{-$locale}/_sidebar-layout/brawlhalla/players/$playerId/{-$tab}': {
      id: '/{-$locale}/_sidebar-layout/brawlhalla/players/$playerId/{-$tab}'
      path: '/brawlhalla/players/$playerId/{-$tab}'
      fullPath: '/{-$locale}/brawlhalla/players/$playerId/{-$tab}'
      preLoaderRoute: typeof Char123LocaleChar125SidebarLayoutBrawlhallaPlayersPlayerIdChar123TabChar125RouteRouteImport
      parentRoute: typeof Char123LocaleChar125SidebarLayoutRouteRoute
    }
  }
}

interface Char123LocaleChar125SidebarLayoutRouteRouteChildren {
  Char123LocaleChar125SidebarLayoutIndexRoute: typeof Char123LocaleChar125SidebarLayoutIndexRoute
  Char123LocaleChar125SidebarLayoutBrawlhallaPlayersPlayerIdChar123TabChar125RouteRoute: typeof Char123LocaleChar125SidebarLayoutBrawlhallaPlayersPlayerIdChar123TabChar125RouteRoute
}

const Char123LocaleChar125SidebarLayoutRouteRouteChildren: Char123LocaleChar125SidebarLayoutRouteRouteChildren =
  {
    Char123LocaleChar125SidebarLayoutIndexRoute:
      Char123LocaleChar125SidebarLayoutIndexRoute,
    Char123LocaleChar125SidebarLayoutBrawlhallaPlayersPlayerIdChar123TabChar125RouteRoute:
      Char123LocaleChar125SidebarLayoutBrawlhallaPlayersPlayerIdChar123TabChar125RouteRoute,
  }

const Char123LocaleChar125SidebarLayoutRouteRouteWithChildren =
  Char123LocaleChar125SidebarLayoutRouteRoute._addFileChildren(
    Char123LocaleChar125SidebarLayoutRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125SidebarLayoutRouteRoute: typeof Char123LocaleChar125SidebarLayoutRouteRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125SidebarLayoutRouteRoute:
      Char123LocaleChar125SidebarLayoutRouteRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
