/* eslint-disable */

// @ts-nocheck

export const safeAssets = [
  '/ads.txt',
  '/assets/images/errors/error-500.png',
  '/assets/images/errors/error-404.png',
  '/assets/images/legends/icons/sidra.png',
  '/assets/images/legends/icons/volkov.png',
  '/assets/images/legends/icons/munin.png',
  '/assets/images/legends/icons/ulgrim.png',
  '/assets/images/legends/icons/hattori.png',
  '/assets/images/legends/icons/arcadia.png',
  '/assets/images/legends/icons/isaiah.png',
  '/assets/images/legends/icons/vivi.png',
  '/assets/images/legends/icons/brynn.png',
  '/assets/images/legends/icons/tezca.png',
  '/assets/images/legends/icons/cross.png',
  '/assets/images/legends/icons/mordex.png',
  '/assets/images/legends/icons/ragnir.png',
  '/assets/images/legends/icons/lord vraxx.png',
  '/assets/images/legends/icons/val.png',
  '/assets/images/legends/icons/petra.png',
  '/assets/images/legends/icons/ezio.png',
  '/assets/images/legends/icons/teros.png',
  '/assets/images/legends/icons/kaya.png',
  '/assets/images/legends/icons/nix.png',
  '/assets/images/legends/icons/mirage.png',
  '/assets/images/legends/icons/scarlet.png',
  '/assets/images/legends/icons/fait.png',
  '/assets/images/legends/icons/queen nai.png',
  '/assets/images/legends/icons/caspian.png',
  '/assets/images/legends/icons/reno.png',
  '/assets/images/legends/icons/sir roland.png',
  '/assets/images/legends/icons/bodvar.png',
  '/assets/images/legends/icons/thor.png',
  '/assets/images/legends/icons/dusk.png',
  '/assets/images/legends/icons/jhala.png',
  '/assets/images/legends/icons/jaeyun.png',
  '/assets/images/legends/icons/loki.png',
  '/assets/images/legends/icons/barraza.png',
  '/assets/images/legends/icons/seven.png',
  '/assets/images/legends/icons/king zuva.png',
  '/assets/images/legends/icons/imugi.png',
  '/assets/images/legends/icons/gnash.png',
  '/assets/images/legends/icons/artemis.png',
  '/assets/images/legends/icons/koji.png',
  '/assets/images/legends/icons/ember.png',
  '/assets/images/legends/icons/sentinel.png',
  '/assets/images/legends/icons/magyar.png',
  '/assets/images/legends/icons/yumiko.png',
  '/assets/images/legends/icons/thatch.png',
  '/assets/images/legends/icons/asuri.png',
  '/assets/images/legends/icons/mako.png',
  '/assets/images/legends/icons/orion.png',
  '/assets/images/legends/icons/azoth.png',
  '/assets/images/legends/icons/rayman.png',
  '/assets/images/legends/icons/vector.png',
  '/assets/images/legends/icons/lin fei.png',
  '/assets/images/legends/icons/kor.png',
  '/assets/images/legends/icons/ada.png',
  '/assets/images/legends/icons/thea.png',
  '/assets/images/legends/icons/onyx.png',
  '/assets/images/legends/icons/diana.png',
  '/assets/images/legends/icons/redraptor.png',
  '/assets/images/legends/icons/xull.png',
  '/assets/images/legends/icons/zariel.png',
  '/assets/images/legends/icons/cassidy.png',
  '/assets/images/legends/icons/wu shang.png',
  '/assets/images/legends/icons/jiro.png',
  '/assets/images/legends/icons/lucien.png',
  '/assets/images/brand/logos/logo-text.png',
  '/assets/images/brand/logos/logo-256x256.png',
  '/assets/images/brand/logos/logo-192x192.png',
  '/assets/images/brand/logos/logo-512x512.png',
  '/assets/images/brand/logos/logo-384x384.png',
  '/assets/images/brand/logos/logo-animated.gif',
  '/assets/images/brand/backgrounds/background-text-sm.jpg',
  '/assets/images/brand/backgrounds/background-text.jpg',
  '/assets/images/brand/backgrounds/background-no-text.jpg',
  '/assets/images/og/main-og.jpg',
  '/assets/images/weapons/icons/Greatsword.png',
  '/assets/images/weapons/icons/Scythe.png',
  '/assets/images/weapons/icons/Katar.png',
  '/assets/images/weapons/icons/Spear.png',
  '/assets/images/weapons/icons/Pistol.png',
  '/assets/images/weapons/icons/Sword.png',
  '/assets/images/weapons/icons/Orb.png',
  '/assets/images/weapons/icons/RocketLance.png',
  '/assets/images/weapons/icons/Boots.png',
  '/assets/images/weapons/icons/Axe.png',
  '/assets/images/weapons/icons/Unarmed.png',
  '/assets/images/weapons/icons/Fists.png',
  '/assets/images/weapons/icons/Hammer.png',
  '/assets/images/weapons/icons/Bow.png',
  '/assets/images/weapons/icons/Cannon.png',
  '/assets/images/ranked/banners/Platinum 3.png',
  '/assets/images/ranked/banners/Tin 4.png',
  '/assets/images/ranked/banners/Bronze 2.png',
  '/assets/images/ranked/banners/Tin 0.png',
  '/assets/images/ranked/banners/Bronze 0.png',
  '/assets/images/ranked/banners/Silver 1.png',
  '/assets/images/ranked/banners/Platinum 1.png',
  '/assets/images/ranked/banners/Valhallan.png',
  '/assets/images/ranked/banners/Gold 1.png',
  '/assets/images/ranked/banners/Tin 3.png',
  '/assets/images/ranked/banners/Diamond.png',
  '/assets/images/ranked/banners/Gold 3.png',
  '/assets/images/ranked/banners/Gold 2.png',
  '/assets/images/ranked/banners/Platinum 0.png',
  '/assets/images/ranked/banners/Gold 0.png',
  '/assets/images/ranked/banners/Tin 1.png',
  '/assets/images/ranked/banners/null.png',
  '/assets/images/ranked/banners/Platinum 4.png',
  '/assets/images/ranked/banners/Silver 0.png',
  '/assets/images/ranked/banners/Silver 3.png',
  '/assets/images/ranked/banners/Silver 5.png',
  '/assets/images/ranked/banners/Bronze 4.png',
  '/assets/images/ranked/banners/Silver 2.png',
  '/assets/images/ranked/banners/Bronze 5.png',
  '/assets/images/ranked/banners/Silver 4.png',
  '/assets/images/ranked/banners/Tin 5.png',
  '/assets/images/ranked/banners/Platinum 2.png',
  '/assets/images/ranked/banners/Bronze 3.png',
  '/assets/images/ranked/banners/Tin 2.png',
  '/assets/images/ranked/banners/Bronze 1.png',
  '/assets/images/ranked/banners/Platinum 5.png',
  '/assets/images/ranked/banners/Gold 4.png',
  '/assets/images/ranked/banners/Emerald.png',
  '/assets/images/ranked/banners/Gold 5.png',
  '/assets/images/ranked/icons/Platinum 3.png',
  '/assets/images/ranked/icons/Tin 4.png',
  '/assets/images/ranked/icons/Bronze 2.png',
  '/assets/images/ranked/icons/Tin 0.png',
  '/assets/images/ranked/icons/Bronze 0.png',
  '/assets/images/ranked/icons/Valhallan.webp',
  '/assets/images/ranked/icons/Silver 1.png',
  '/assets/images/ranked/icons/Platinum 1.png',
  '/assets/images/ranked/icons/Gold 1.png',
  '/assets/images/ranked/icons/Tin 3.png',
  '/assets/images/ranked/icons/Diamond.png',
  '/assets/images/ranked/icons/Gold 3.png',
  '/assets/images/ranked/icons/Gold 2.png',
  '/assets/images/ranked/icons/Platinum 0.png',
  '/assets/images/ranked/icons/Gold 0.png',
  '/assets/images/ranked/icons/Tin 1.png',
  '/assets/images/ranked/icons/Platinum 4.png',
  '/assets/images/ranked/icons/Silver 0.png',
  '/assets/images/ranked/icons/Silver 3.png',
  '/assets/images/ranked/icons/Silver 5.png',
  '/assets/images/ranked/icons/Bronze 4.png',
  '/assets/images/ranked/icons/Silver 2.png',
  '/assets/images/ranked/icons/Bronze 5.png',
  '/assets/images/ranked/icons/Silver 4.png',
  '/assets/images/ranked/icons/Tin 5.png',
  '/assets/images/ranked/icons/Platinum 2.png',
  '/assets/images/ranked/icons/Bronze 3.png',
  '/assets/images/ranked/icons/Tin 2.png',
  '/assets/images/ranked/icons/Bronze 1.png',
  '/assets/images/ranked/icons/Platinum 5.png',
  '/assets/images/ranked/icons/Gold 4.png',
  '/assets/images/ranked/icons/Gold 5.png',
  '/assets/images/games/cupcakes/grandma.svg',
  '/assets/images/games/cupcakes/farms.svg',
  '/assets/images/games/cupcakes/scarlet.svg',
  '/assets/images/games/cupcakes/kitchen.svg',
  '/assets/images/games/cupcakes/celestial.svg',
  '/assets/images/games/cupcakes/orion.svg',
  '/assets/images/games/cupcakes/cupcake.svg',
  '/assets/images/games/cupcakes/helpers.svg',
  '/assets/images/games/cupcakes/ivaldi.svg',
  '/assets/images/games/cupcakes/grimm.svg',
  '/assets/images/flags/us-e.png',
  '/assets/images/flags/aus.png',
  '/assets/images/flags/sea.png',
  '/assets/images/flags/jpn.png',
  '/assets/images/flags/me.png',
  '/assets/images/flags/eu.png',
  '/assets/images/flags/all.png',
  '/assets/images/flags/brz.png',
  '/assets/images/flags/sa.png',
  '/assets/images/flags/us-w.png',
  '/assets/images/grain.png',
  '/robots.txt',
  '/favicon.png',
] as const;

export type SafeAsset = (typeof safeAssets)[number];

export const assetsTree = {
  'ads.txt': '/ads.txt',
  assets: {
    images: {
      errors: {
        'error-500.png': '/assets/images/errors/error-500.png',
        'error-404.png': '/assets/images/errors/error-404.png',
      },
      legends: {
        icons: {
          'sidra.png': '/assets/images/legends/icons/sidra.png',
          'volkov.png': '/assets/images/legends/icons/volkov.png',
          'munin.png': '/assets/images/legends/icons/munin.png',
          'ulgrim.png': '/assets/images/legends/icons/ulgrim.png',
          'hattori.png': '/assets/images/legends/icons/hattori.png',
          'arcadia.png': '/assets/images/legends/icons/arcadia.png',
          'isaiah.png': '/assets/images/legends/icons/isaiah.png',
          'vivi.png': '/assets/images/legends/icons/vivi.png',
          'brynn.png': '/assets/images/legends/icons/brynn.png',
          'tezca.png': '/assets/images/legends/icons/tezca.png',
          'cross.png': '/assets/images/legends/icons/cross.png',
          'mordex.png': '/assets/images/legends/icons/mordex.png',
          'ragnir.png': '/assets/images/legends/icons/ragnir.png',
          'lord vraxx.png': '/assets/images/legends/icons/lord vraxx.png',
          'val.png': '/assets/images/legends/icons/val.png',
          'petra.png': '/assets/images/legends/icons/petra.png',
          'ezio.png': '/assets/images/legends/icons/ezio.png',
          'teros.png': '/assets/images/legends/icons/teros.png',
          'kaya.png': '/assets/images/legends/icons/kaya.png',
          'nix.png': '/assets/images/legends/icons/nix.png',
          'mirage.png': '/assets/images/legends/icons/mirage.png',
          'scarlet.png': '/assets/images/legends/icons/scarlet.png',
          'fait.png': '/assets/images/legends/icons/fait.png',
          'queen nai.png': '/assets/images/legends/icons/queen nai.png',
          'caspian.png': '/assets/images/legends/icons/caspian.png',
          'reno.png': '/assets/images/legends/icons/reno.png',
          'sir roland.png': '/assets/images/legends/icons/sir roland.png',
          'bodvar.png': '/assets/images/legends/icons/bodvar.png',
          'thor.png': '/assets/images/legends/icons/thor.png',
          'dusk.png': '/assets/images/legends/icons/dusk.png',
          'jhala.png': '/assets/images/legends/icons/jhala.png',
          'jaeyun.png': '/assets/images/legends/icons/jaeyun.png',
          'loki.png': '/assets/images/legends/icons/loki.png',
          'barraza.png': '/assets/images/legends/icons/barraza.png',
          'seven.png': '/assets/images/legends/icons/seven.png',
          'king zuva.png': '/assets/images/legends/icons/king zuva.png',
          'imugi.png': '/assets/images/legends/icons/imugi.png',
          'gnash.png': '/assets/images/legends/icons/gnash.png',
          'artemis.png': '/assets/images/legends/icons/artemis.png',
          'koji.png': '/assets/images/legends/icons/koji.png',
          'ember.png': '/assets/images/legends/icons/ember.png',
          'sentinel.png': '/assets/images/legends/icons/sentinel.png',
          'magyar.png': '/assets/images/legends/icons/magyar.png',
          'yumiko.png': '/assets/images/legends/icons/yumiko.png',
          'thatch.png': '/assets/images/legends/icons/thatch.png',
          'asuri.png': '/assets/images/legends/icons/asuri.png',
          'mako.png': '/assets/images/legends/icons/mako.png',
          'orion.png': '/assets/images/legends/icons/orion.png',
          'azoth.png': '/assets/images/legends/icons/azoth.png',
          'rayman.png': '/assets/images/legends/icons/rayman.png',
          'vector.png': '/assets/images/legends/icons/vector.png',
          'lin fei.png': '/assets/images/legends/icons/lin fei.png',
          'kor.png': '/assets/images/legends/icons/kor.png',
          'ada.png': '/assets/images/legends/icons/ada.png',
          'thea.png': '/assets/images/legends/icons/thea.png',
          'onyx.png': '/assets/images/legends/icons/onyx.png',
          'diana.png': '/assets/images/legends/icons/diana.png',
          'redraptor.png': '/assets/images/legends/icons/redraptor.png',
          'xull.png': '/assets/images/legends/icons/xull.png',
          'zariel.png': '/assets/images/legends/icons/zariel.png',
          'cassidy.png': '/assets/images/legends/icons/cassidy.png',
          'wu shang.png': '/assets/images/legends/icons/wu shang.png',
          'jiro.png': '/assets/images/legends/icons/jiro.png',
          'lucien.png': '/assets/images/legends/icons/lucien.png',
        },
      },
      brand: {
        logos: {
          'logo-text.png': '/assets/images/brand/logos/logo-text.png',
          'logo-256x256.png': '/assets/images/brand/logos/logo-256x256.png',
          'logo-192x192.png': '/assets/images/brand/logos/logo-192x192.png',
          'logo-512x512.png': '/assets/images/brand/logos/logo-512x512.png',
          'logo-384x384.png': '/assets/images/brand/logos/logo-384x384.png',
          'logo-animated.gif': '/assets/images/brand/logos/logo-animated.gif',
        },
        backgrounds: {
          'background-text-sm.jpg': '/assets/images/brand/backgrounds/background-text-sm.jpg',
          'background-text.jpg': '/assets/images/brand/backgrounds/background-text.jpg',
          'background-no-text.jpg': '/assets/images/brand/backgrounds/background-no-text.jpg',
        },
      },
      og: {
        'main-og.jpg': '/assets/images/og/main-og.jpg',
      },
      weapons: {
        icons: {
          'Greatsword.png': '/assets/images/weapons/icons/Greatsword.png',
          'Scythe.png': '/assets/images/weapons/icons/Scythe.png',
          'Katar.png': '/assets/images/weapons/icons/Katar.png',
          'Spear.png': '/assets/images/weapons/icons/Spear.png',
          'Pistol.png': '/assets/images/weapons/icons/Pistol.png',
          'Sword.png': '/assets/images/weapons/icons/Sword.png',
          'Orb.png': '/assets/images/weapons/icons/Orb.png',
          'RocketLance.png': '/assets/images/weapons/icons/RocketLance.png',
          'Boots.png': '/assets/images/weapons/icons/Boots.png',
          'Axe.png': '/assets/images/weapons/icons/Axe.png',
          'Unarmed.png': '/assets/images/weapons/icons/Unarmed.png',
          'Fists.png': '/assets/images/weapons/icons/Fists.png',
          'Hammer.png': '/assets/images/weapons/icons/Hammer.png',
          'Bow.png': '/assets/images/weapons/icons/Bow.png',
          'Cannon.png': '/assets/images/weapons/icons/Cannon.png',
        },
      },
      ranked: {
        banners: {
          'Platinum 3.png': '/assets/images/ranked/banners/Platinum 3.png',
          'Tin 4.png': '/assets/images/ranked/banners/Tin 4.png',
          'Bronze 2.png': '/assets/images/ranked/banners/Bronze 2.png',
          'Tin 0.png': '/assets/images/ranked/banners/Tin 0.png',
          'Bronze 0.png': '/assets/images/ranked/banners/Bronze 0.png',
          'Silver 1.png': '/assets/images/ranked/banners/Silver 1.png',
          'Platinum 1.png': '/assets/images/ranked/banners/Platinum 1.png',
          'Valhallan.png': '/assets/images/ranked/banners/Valhallan.png',
          'Gold 1.png': '/assets/images/ranked/banners/Gold 1.png',
          'Tin 3.png': '/assets/images/ranked/banners/Tin 3.png',
          'Diamond.png': '/assets/images/ranked/banners/Diamond.png',
          'Gold 3.png': '/assets/images/ranked/banners/Gold 3.png',
          'Gold 2.png': '/assets/images/ranked/banners/Gold 2.png',
          'Platinum 0.png': '/assets/images/ranked/banners/Platinum 0.png',
          'Gold 0.png': '/assets/images/ranked/banners/Gold 0.png',
          'Tin 1.png': '/assets/images/ranked/banners/Tin 1.png',
          'null.png': '/assets/images/ranked/banners/null.png',
          'Platinum 4.png': '/assets/images/ranked/banners/Platinum 4.png',
          'Silver 0.png': '/assets/images/ranked/banners/Silver 0.png',
          'Silver 3.png': '/assets/images/ranked/banners/Silver 3.png',
          'Silver 5.png': '/assets/images/ranked/banners/Silver 5.png',
          'Bronze 4.png': '/assets/images/ranked/banners/Bronze 4.png',
          'Silver 2.png': '/assets/images/ranked/banners/Silver 2.png',
          'Bronze 5.png': '/assets/images/ranked/banners/Bronze 5.png',
          'Silver 4.png': '/assets/images/ranked/banners/Silver 4.png',
          'Tin 5.png': '/assets/images/ranked/banners/Tin 5.png',
          'Platinum 2.png': '/assets/images/ranked/banners/Platinum 2.png',
          'Bronze 3.png': '/assets/images/ranked/banners/Bronze 3.png',
          'Tin 2.png': '/assets/images/ranked/banners/Tin 2.png',
          'Bronze 1.png': '/assets/images/ranked/banners/Bronze 1.png',
          'Platinum 5.png': '/assets/images/ranked/banners/Platinum 5.png',
          'Gold 4.png': '/assets/images/ranked/banners/Gold 4.png',
          'Emerald.png': '/assets/images/ranked/banners/Emerald.png',
          'Gold 5.png': '/assets/images/ranked/banners/Gold 5.png',
        },
        icons: {
          'Platinum 3.png': '/assets/images/ranked/icons/Platinum 3.png',
          'Tin 4.png': '/assets/images/ranked/icons/Tin 4.png',
          'Bronze 2.png': '/assets/images/ranked/icons/Bronze 2.png',
          'Tin 0.png': '/assets/images/ranked/icons/Tin 0.png',
          'Bronze 0.png': '/assets/images/ranked/icons/Bronze 0.png',
          'Valhallan.webp': '/assets/images/ranked/icons/Valhallan.webp',
          'Silver 1.png': '/assets/images/ranked/icons/Silver 1.png',
          'Platinum 1.png': '/assets/images/ranked/icons/Platinum 1.png',
          'Gold 1.png': '/assets/images/ranked/icons/Gold 1.png',
          'Tin 3.png': '/assets/images/ranked/icons/Tin 3.png',
          'Diamond.png': '/assets/images/ranked/icons/Diamond.png',
          'Gold 3.png': '/assets/images/ranked/icons/Gold 3.png',
          'Gold 2.png': '/assets/images/ranked/icons/Gold 2.png',
          'Platinum 0.png': '/assets/images/ranked/icons/Platinum 0.png',
          'Gold 0.png': '/assets/images/ranked/icons/Gold 0.png',
          'Tin 1.png': '/assets/images/ranked/icons/Tin 1.png',
          'Platinum 4.png': '/assets/images/ranked/icons/Platinum 4.png',
          'Silver 0.png': '/assets/images/ranked/icons/Silver 0.png',
          'Silver 3.png': '/assets/images/ranked/icons/Silver 3.png',
          'Silver 5.png': '/assets/images/ranked/icons/Silver 5.png',
          'Bronze 4.png': '/assets/images/ranked/icons/Bronze 4.png',
          'Silver 2.png': '/assets/images/ranked/icons/Silver 2.png',
          'Bronze 5.png': '/assets/images/ranked/icons/Bronze 5.png',
          'Silver 4.png': '/assets/images/ranked/icons/Silver 4.png',
          'Tin 5.png': '/assets/images/ranked/icons/Tin 5.png',
          'Platinum 2.png': '/assets/images/ranked/icons/Platinum 2.png',
          'Bronze 3.png': '/assets/images/ranked/icons/Bronze 3.png',
          'Tin 2.png': '/assets/images/ranked/icons/Tin 2.png',
          'Bronze 1.png': '/assets/images/ranked/icons/Bronze 1.png',
          'Platinum 5.png': '/assets/images/ranked/icons/Platinum 5.png',
          'Gold 4.png': '/assets/images/ranked/icons/Gold 4.png',
          'Gold 5.png': '/assets/images/ranked/icons/Gold 5.png',
        },
      },
      games: {
        cupcakes: {
          'grandma.svg': '/assets/images/games/cupcakes/grandma.svg',
          'farms.svg': '/assets/images/games/cupcakes/farms.svg',
          'scarlet.svg': '/assets/images/games/cupcakes/scarlet.svg',
          'kitchen.svg': '/assets/images/games/cupcakes/kitchen.svg',
          'celestial.svg': '/assets/images/games/cupcakes/celestial.svg',
          'orion.svg': '/assets/images/games/cupcakes/orion.svg',
          'cupcake.svg': '/assets/images/games/cupcakes/cupcake.svg',
          'helpers.svg': '/assets/images/games/cupcakes/helpers.svg',
          'ivaldi.svg': '/assets/images/games/cupcakes/ivaldi.svg',
          'grimm.svg': '/assets/images/games/cupcakes/grimm.svg',
        },
      },
      flags: {
        'us-e.png': '/assets/images/flags/us-e.png',
        'aus.png': '/assets/images/flags/aus.png',
        'sea.png': '/assets/images/flags/sea.png',
        'jpn.png': '/assets/images/flags/jpn.png',
        'me.png': '/assets/images/flags/me.png',
        'eu.png': '/assets/images/flags/eu.png',
        'all.png': '/assets/images/flags/all.png',
        'brz.png': '/assets/images/flags/brz.png',
        'sa.png': '/assets/images/flags/sa.png',
        'us-w.png': '/assets/images/flags/us-w.png',
      },
      'grain.png': '/assets/images/grain.png',
    },
  },
  'robots.txt': '/robots.txt',
  'favicon.png': '/favicon.png',
} as const;
