/* eslint-disable */

// @ts-nocheck

export const safeAssets = [
  "/ads.txt",
  "/favicon.png",
  "/robots.txt",
  "/assets/images/ranked/banners/Emerald.png",
  "/assets/images/ranked/banners/Platinum 0.png",
  "/assets/images/ranked/banners/Platinum 1.png",
  "/assets/images/ranked/banners/Platinum 3.png",
  "/assets/images/ranked/banners/Platinum 2.png",
  "/assets/images/ranked/banners/Valhallan.png",
  "/assets/images/ranked/banners/Platinum 5.png",
  "/assets/images/ranked/banners/Platinum 4.png",
  "/assets/images/ranked/banners/Bronze 1.png",
  "/assets/images/ranked/banners/Bronze 0.png",
  "/assets/images/ranked/banners/Bronze 2.png",
  "/assets/images/ranked/banners/Bronze 3.png",
  "/assets/images/ranked/banners/Bronze 4.png",
  "/assets/images/ranked/banners/Bronze 5.png",
  "/assets/images/ranked/banners/Silver 3.png",
  "/assets/images/ranked/banners/Silver 2.png",
  "/assets/images/ranked/banners/Silver 0.png",
  "/assets/images/ranked/banners/Tin 5.png",
  "/assets/images/ranked/banners/null.png",
  "/assets/images/ranked/banners/Tin 4.png",
  "/assets/images/ranked/banners/Silver 1.png",
  "/assets/images/ranked/banners/Tin 0.png",
  "/assets/images/ranked/banners/Silver 5.png",
  "/assets/images/ranked/banners/Silver 4.png",
  "/assets/images/ranked/banners/Tin 1.png",
  "/assets/images/ranked/banners/Tin 3.png",
  "/assets/images/ranked/banners/Tin 2.png",
  "/assets/images/ranked/banners/Diamond.png",
  "/assets/images/ranked/banners/Gold 4.png",
  "/assets/images/ranked/banners/Gold 5.png",
  "/assets/images/ranked/banners/Gold 1.png",
  "/assets/images/ranked/banners/Gold 0.png",
  "/assets/images/ranked/banners/Gold 2.png",
  "/assets/images/ranked/banners/Gold 3.png",
  "/assets/images/ranked/icons/Platinum 0.png",
  "/assets/images/ranked/icons/Platinum 1.png",
  "/assets/images/ranked/icons/Platinum 3.png",
  "/assets/images/ranked/icons/Platinum 2.png",
  "/assets/images/ranked/icons/Platinum 5.png",
  "/assets/images/ranked/icons/Platinum 4.png",
  "/assets/images/ranked/icons/Bronze 1.png",
  "/assets/images/ranked/icons/Bronze 0.png",
  "/assets/images/ranked/icons/Bronze 2.png",
  "/assets/images/ranked/icons/Valhallan.webp",
  "/assets/images/ranked/icons/Bronze 3.png",
  "/assets/images/ranked/icons/Bronze 4.png",
  "/assets/images/ranked/icons/Bronze 5.png",
  "/assets/images/ranked/icons/Silver 3.png",
  "/assets/images/ranked/icons/Silver 2.png",
  "/assets/images/ranked/icons/Silver 0.png",
  "/assets/images/ranked/icons/Tin 5.png",
  "/assets/images/ranked/icons/Tin 4.png",
  "/assets/images/ranked/icons/Silver 1.png",
  "/assets/images/ranked/icons/Tin 0.png",
  "/assets/images/ranked/icons/Silver 5.png",
  "/assets/images/ranked/icons/Silver 4.png",
  "/assets/images/ranked/icons/Tin 1.png",
  "/assets/images/ranked/icons/Tin 3.png",
  "/assets/images/ranked/icons/Tin 2.png",
  "/assets/images/ranked/icons/Diamond.png",
  "/assets/images/ranked/icons/Gold 4.png",
  "/assets/images/ranked/icons/Gold 5.png",
  "/assets/images/ranked/icons/Gold 1.png",
  "/assets/images/ranked/icons/Gold 0.png",
  "/assets/images/ranked/icons/Gold 2.png",
  "/assets/images/ranked/icons/Gold 3.png",
  "/assets/images/flags/me.png",
  "/assets/images/flags/us-w.png",
  "/assets/images/flags/us-e.png",
  "/assets/images/flags/all.png",
  "/assets/images/flags/sa.png",
  "/assets/images/flags/jpn.png",
  "/assets/images/flags/brz.png",
  "/assets/images/flags/aus.png",
  "/assets/images/flags/sea.png",
  "/assets/images/flags/eu.png",
  "/assets/images/legends/icons/lord vraxx.png",
  "/assets/images/legends/icons/orion.png",
  "/assets/images/legends/icons/arcadia.png",
  "/assets/images/legends/icons/caspian.png",
  "/assets/images/legends/icons/isaiah.png",
  "/assets/images/legends/icons/fait.png",
  "/assets/images/legends/icons/redraptor.png",
  "/assets/images/legends/icons/cassidy.png",
  "/assets/images/legends/icons/onyx.png",
  "/assets/images/legends/icons/jhala.png",
  "/assets/images/legends/icons/mordex.png",
  "/assets/images/legends/icons/tezca.png",
  "/assets/images/legends/icons/gnash.png",
  "/assets/images/legends/icons/kaya.png",
  "/assets/images/legends/icons/ragnir.png",
  "/assets/images/legends/icons/ulgrim.png",
  "/assets/images/legends/icons/vivi.png",
  "/assets/images/legends/icons/yumiko.png",
  "/assets/images/legends/icons/ada.png",
  "/assets/images/legends/icons/lin fei.png",
  "/assets/images/legends/icons/azoth.png",
  "/assets/images/legends/icons/bodvar.png",
  "/assets/images/legends/icons/king zuva.png",
  "/assets/images/legends/icons/nix.png",
  "/assets/images/legends/icons/wu shang.png",
  "/assets/images/legends/icons/koji.png",
  "/assets/images/legends/icons/ezio.png",
  "/assets/images/legends/icons/vector.png",
  "/assets/images/legends/icons/magyar.png",
  "/assets/images/legends/icons/brynn.png",
  "/assets/images/legends/icons/rayman.png",
  "/assets/images/legends/icons/sidra.png",
  "/assets/images/legends/icons/munin.png",
  "/assets/images/legends/icons/val.png",
  "/assets/images/legends/icons/hattori.png",
  "/assets/images/legends/icons/ember.png",
  "/assets/images/legends/icons/reno.png",
  "/assets/images/legends/icons/cross.png",
  "/assets/images/legends/icons/petra.png",
  "/assets/images/legends/icons/kor.png",
  "/assets/images/legends/icons/dusk.png",
  "/assets/images/legends/icons/xull.png",
  "/assets/images/legends/icons/loki.png",
  "/assets/images/legends/icons/artemis.png",
  "/assets/images/legends/icons/queen nai.png",
  "/assets/images/legends/icons/imugi.png",
  "/assets/images/legends/icons/zariel.png",
  "/assets/images/legends/icons/barraza.png",
  "/assets/images/legends/icons/thor.png",
  "/assets/images/legends/icons/volkov.png",
  "/assets/images/legends/icons/sir roland.png",
  "/assets/images/legends/icons/thea.png",
  "/assets/images/legends/icons/mirage.png",
  "/assets/images/legends/icons/sentinel.png",
  "/assets/images/legends/icons/diana.png",
  "/assets/images/legends/icons/seven.png",
  "/assets/images/legends/icons/asuri.png",
  "/assets/images/legends/icons/jaeyun.png",
  "/assets/images/legends/icons/thatch.png",
  "/assets/images/legends/icons/jiro.png",
  "/assets/images/legends/icons/mako.png",
  "/assets/images/legends/icons/teros.png",
  "/assets/images/legends/icons/scarlet.png",
  "/assets/images/legends/icons/lucien.png",
  "/assets/images/brand/logos/logo-animated.gif",
  "/assets/images/brand/logos/logo-512x512.png",
  "/assets/images/brand/logos/logo-384x384.png",
  "/assets/images/brand/logos/logo-text.png",
  "/assets/images/brand/logos/logo-192x192.png",
  "/assets/images/brand/logos/logo-256x256.png",
  "/assets/images/brand/backgrounds/background-text.jpg",
  "/assets/images/brand/backgrounds/background-text-sm.jpg",
  "/assets/images/brand/backgrounds/background-no-text.jpg",
  "/assets/images/weapons/icons/Boots.png",
  "/assets/images/weapons/icons/Bow.png",
  "/assets/images/weapons/icons/Katar.png",
  "/assets/images/weapons/icons/Orb.png",
  "/assets/images/weapons/icons/Scythe.png",
  "/assets/images/weapons/icons/Pistol.png",
  "/assets/images/weapons/icons/Greatsword.png",
  "/assets/images/weapons/icons/Sword.png",
  "/assets/images/weapons/icons/Cannon.png",
  "/assets/images/weapons/icons/Axe.png",
  "/assets/images/weapons/icons/RocketLance.png",
  "/assets/images/weapons/icons/Hammer.png",
  "/assets/images/weapons/icons/Spear.png",
  "/assets/images/weapons/icons/Unarmed.png",
  "/assets/images/weapons/icons/Fists.png",
  "/assets/images/errors/error-500.png",
  "/assets/images/errors/error-404.png",
  "/assets/images/og/main-og.jpg",
  "/assets/images/games/cupcakes/grandma.svg",
  "/assets/images/games/cupcakes/celestial.svg",
  "/assets/images/games/cupcakes/ivaldi.svg",
  "/assets/images/games/cupcakes/orion.svg",
  "/assets/images/games/cupcakes/scarlet.svg",
  "/assets/images/games/cupcakes/grimm.svg",
  "/assets/images/games/cupcakes/cupcake.svg",
  "/assets/images/games/cupcakes/helpers.svg",
  "/assets/images/games/cupcakes/kitchen.svg",
  "/assets/images/games/cupcakes/farms.svg"
] as const;

export type SafeAsset = typeof safeAssets[number];

export const assetsTree = {
  "ads.txt": "/ads.txt",
  "favicon.png": "/favicon.png",
  "robots.txt": "/robots.txt",
  "assets": {
    "images": {
      "ranked": {
        "banners": {
          "Emerald.png": "/assets/images/ranked/banners/Emerald.png",
          "Platinum 0.png": "/assets/images/ranked/banners/Platinum 0.png",
          "Platinum 1.png": "/assets/images/ranked/banners/Platinum 1.png",
          "Platinum 3.png": "/assets/images/ranked/banners/Platinum 3.png",
          "Platinum 2.png": "/assets/images/ranked/banners/Platinum 2.png",
          "Valhallan.png": "/assets/images/ranked/banners/Valhallan.png",
          "Platinum 5.png": "/assets/images/ranked/banners/Platinum 5.png",
          "Platinum 4.png": "/assets/images/ranked/banners/Platinum 4.png",
          "Bronze 1.png": "/assets/images/ranked/banners/Bronze 1.png",
          "Bronze 0.png": "/assets/images/ranked/banners/Bronze 0.png",
          "Bronze 2.png": "/assets/images/ranked/banners/Bronze 2.png",
          "Bronze 3.png": "/assets/images/ranked/banners/Bronze 3.png",
          "Bronze 4.png": "/assets/images/ranked/banners/Bronze 4.png",
          "Bronze 5.png": "/assets/images/ranked/banners/Bronze 5.png",
          "Silver 3.png": "/assets/images/ranked/banners/Silver 3.png",
          "Silver 2.png": "/assets/images/ranked/banners/Silver 2.png",
          "Silver 0.png": "/assets/images/ranked/banners/Silver 0.png",
          "Tin 5.png": "/assets/images/ranked/banners/Tin 5.png",
          "null.png": "/assets/images/ranked/banners/null.png",
          "Tin 4.png": "/assets/images/ranked/banners/Tin 4.png",
          "Silver 1.png": "/assets/images/ranked/banners/Silver 1.png",
          "Tin 0.png": "/assets/images/ranked/banners/Tin 0.png",
          "Silver 5.png": "/assets/images/ranked/banners/Silver 5.png",
          "Silver 4.png": "/assets/images/ranked/banners/Silver 4.png",
          "Tin 1.png": "/assets/images/ranked/banners/Tin 1.png",
          "Tin 3.png": "/assets/images/ranked/banners/Tin 3.png",
          "Tin 2.png": "/assets/images/ranked/banners/Tin 2.png",
          "Diamond.png": "/assets/images/ranked/banners/Diamond.png",
          "Gold 4.png": "/assets/images/ranked/banners/Gold 4.png",
          "Gold 5.png": "/assets/images/ranked/banners/Gold 5.png",
          "Gold 1.png": "/assets/images/ranked/banners/Gold 1.png",
          "Gold 0.png": "/assets/images/ranked/banners/Gold 0.png",
          "Gold 2.png": "/assets/images/ranked/banners/Gold 2.png",
          "Gold 3.png": "/assets/images/ranked/banners/Gold 3.png"
        },
        "icons": {
          "Platinum 0.png": "/assets/images/ranked/icons/Platinum 0.png",
          "Platinum 1.png": "/assets/images/ranked/icons/Platinum 1.png",
          "Platinum 3.png": "/assets/images/ranked/icons/Platinum 3.png",
          "Platinum 2.png": "/assets/images/ranked/icons/Platinum 2.png",
          "Platinum 5.png": "/assets/images/ranked/icons/Platinum 5.png",
          "Platinum 4.png": "/assets/images/ranked/icons/Platinum 4.png",
          "Bronze 1.png": "/assets/images/ranked/icons/Bronze 1.png",
          "Bronze 0.png": "/assets/images/ranked/icons/Bronze 0.png",
          "Bronze 2.png": "/assets/images/ranked/icons/Bronze 2.png",
          "Valhallan.webp": "/assets/images/ranked/icons/Valhallan.webp",
          "Bronze 3.png": "/assets/images/ranked/icons/Bronze 3.png",
          "Bronze 4.png": "/assets/images/ranked/icons/Bronze 4.png",
          "Bronze 5.png": "/assets/images/ranked/icons/Bronze 5.png",
          "Silver 3.png": "/assets/images/ranked/icons/Silver 3.png",
          "Silver 2.png": "/assets/images/ranked/icons/Silver 2.png",
          "Silver 0.png": "/assets/images/ranked/icons/Silver 0.png",
          "Tin 5.png": "/assets/images/ranked/icons/Tin 5.png",
          "Tin 4.png": "/assets/images/ranked/icons/Tin 4.png",
          "Silver 1.png": "/assets/images/ranked/icons/Silver 1.png",
          "Tin 0.png": "/assets/images/ranked/icons/Tin 0.png",
          "Silver 5.png": "/assets/images/ranked/icons/Silver 5.png",
          "Silver 4.png": "/assets/images/ranked/icons/Silver 4.png",
          "Tin 1.png": "/assets/images/ranked/icons/Tin 1.png",
          "Tin 3.png": "/assets/images/ranked/icons/Tin 3.png",
          "Tin 2.png": "/assets/images/ranked/icons/Tin 2.png",
          "Diamond.png": "/assets/images/ranked/icons/Diamond.png",
          "Gold 4.png": "/assets/images/ranked/icons/Gold 4.png",
          "Gold 5.png": "/assets/images/ranked/icons/Gold 5.png",
          "Gold 1.png": "/assets/images/ranked/icons/Gold 1.png",
          "Gold 0.png": "/assets/images/ranked/icons/Gold 0.png",
          "Gold 2.png": "/assets/images/ranked/icons/Gold 2.png",
          "Gold 3.png": "/assets/images/ranked/icons/Gold 3.png"
        }
      },
      "flags": {
        "me.png": "/assets/images/flags/me.png",
        "us-w.png": "/assets/images/flags/us-w.png",
        "us-e.png": "/assets/images/flags/us-e.png",
        "all.png": "/assets/images/flags/all.png",
        "sa.png": "/assets/images/flags/sa.png",
        "jpn.png": "/assets/images/flags/jpn.png",
        "brz.png": "/assets/images/flags/brz.png",
        "aus.png": "/assets/images/flags/aus.png",
        "sea.png": "/assets/images/flags/sea.png",
        "eu.png": "/assets/images/flags/eu.png"
      },
      "legends": {
        "icons": {
          "lord vraxx.png": "/assets/images/legends/icons/lord vraxx.png",
          "orion.png": "/assets/images/legends/icons/orion.png",
          "arcadia.png": "/assets/images/legends/icons/arcadia.png",
          "caspian.png": "/assets/images/legends/icons/caspian.png",
          "isaiah.png": "/assets/images/legends/icons/isaiah.png",
          "fait.png": "/assets/images/legends/icons/fait.png",
          "redraptor.png": "/assets/images/legends/icons/redraptor.png",
          "cassidy.png": "/assets/images/legends/icons/cassidy.png",
          "onyx.png": "/assets/images/legends/icons/onyx.png",
          "jhala.png": "/assets/images/legends/icons/jhala.png",
          "mordex.png": "/assets/images/legends/icons/mordex.png",
          "tezca.png": "/assets/images/legends/icons/tezca.png",
          "gnash.png": "/assets/images/legends/icons/gnash.png",
          "kaya.png": "/assets/images/legends/icons/kaya.png",
          "ragnir.png": "/assets/images/legends/icons/ragnir.png",
          "ulgrim.png": "/assets/images/legends/icons/ulgrim.png",
          "vivi.png": "/assets/images/legends/icons/vivi.png",
          "yumiko.png": "/assets/images/legends/icons/yumiko.png",
          "ada.png": "/assets/images/legends/icons/ada.png",
          "lin fei.png": "/assets/images/legends/icons/lin fei.png",
          "azoth.png": "/assets/images/legends/icons/azoth.png",
          "bodvar.png": "/assets/images/legends/icons/bodvar.png",
          "king zuva.png": "/assets/images/legends/icons/king zuva.png",
          "nix.png": "/assets/images/legends/icons/nix.png",
          "wu shang.png": "/assets/images/legends/icons/wu shang.png",
          "koji.png": "/assets/images/legends/icons/koji.png",
          "ezio.png": "/assets/images/legends/icons/ezio.png",
          "vector.png": "/assets/images/legends/icons/vector.png",
          "magyar.png": "/assets/images/legends/icons/magyar.png",
          "brynn.png": "/assets/images/legends/icons/brynn.png",
          "rayman.png": "/assets/images/legends/icons/rayman.png",
          "sidra.png": "/assets/images/legends/icons/sidra.png",
          "munin.png": "/assets/images/legends/icons/munin.png",
          "val.png": "/assets/images/legends/icons/val.png",
          "hattori.png": "/assets/images/legends/icons/hattori.png",
          "ember.png": "/assets/images/legends/icons/ember.png",
          "reno.png": "/assets/images/legends/icons/reno.png",
          "cross.png": "/assets/images/legends/icons/cross.png",
          "petra.png": "/assets/images/legends/icons/petra.png",
          "kor.png": "/assets/images/legends/icons/kor.png",
          "dusk.png": "/assets/images/legends/icons/dusk.png",
          "xull.png": "/assets/images/legends/icons/xull.png",
          "loki.png": "/assets/images/legends/icons/loki.png",
          "artemis.png": "/assets/images/legends/icons/artemis.png",
          "queen nai.png": "/assets/images/legends/icons/queen nai.png",
          "imugi.png": "/assets/images/legends/icons/imugi.png",
          "zariel.png": "/assets/images/legends/icons/zariel.png",
          "barraza.png": "/assets/images/legends/icons/barraza.png",
          "thor.png": "/assets/images/legends/icons/thor.png",
          "volkov.png": "/assets/images/legends/icons/volkov.png",
          "sir roland.png": "/assets/images/legends/icons/sir roland.png",
          "thea.png": "/assets/images/legends/icons/thea.png",
          "mirage.png": "/assets/images/legends/icons/mirage.png",
          "sentinel.png": "/assets/images/legends/icons/sentinel.png",
          "diana.png": "/assets/images/legends/icons/diana.png",
          "seven.png": "/assets/images/legends/icons/seven.png",
          "asuri.png": "/assets/images/legends/icons/asuri.png",
          "jaeyun.png": "/assets/images/legends/icons/jaeyun.png",
          "thatch.png": "/assets/images/legends/icons/thatch.png",
          "jiro.png": "/assets/images/legends/icons/jiro.png",
          "mako.png": "/assets/images/legends/icons/mako.png",
          "teros.png": "/assets/images/legends/icons/teros.png",
          "scarlet.png": "/assets/images/legends/icons/scarlet.png",
          "lucien.png": "/assets/images/legends/icons/lucien.png"
        }
      },
      "brand": {
        "logos": {
          "logo-animated.gif": "/assets/images/brand/logos/logo-animated.gif",
          "logo-512x512.png": "/assets/images/brand/logos/logo-512x512.png",
          "logo-384x384.png": "/assets/images/brand/logos/logo-384x384.png",
          "logo-text.png": "/assets/images/brand/logos/logo-text.png",
          "logo-192x192.png": "/assets/images/brand/logos/logo-192x192.png",
          "logo-256x256.png": "/assets/images/brand/logos/logo-256x256.png"
        },
        "backgrounds": {
          "background-text.jpg": "/assets/images/brand/backgrounds/background-text.jpg",
          "background-text-sm.jpg": "/assets/images/brand/backgrounds/background-text-sm.jpg",
          "background-no-text.jpg": "/assets/images/brand/backgrounds/background-no-text.jpg"
        }
      },
      "weapons": {
        "icons": {
          "Boots.png": "/assets/images/weapons/icons/Boots.png",
          "Bow.png": "/assets/images/weapons/icons/Bow.png",
          "Katar.png": "/assets/images/weapons/icons/Katar.png",
          "Orb.png": "/assets/images/weapons/icons/Orb.png",
          "Scythe.png": "/assets/images/weapons/icons/Scythe.png",
          "Pistol.png": "/assets/images/weapons/icons/Pistol.png",
          "Greatsword.png": "/assets/images/weapons/icons/Greatsword.png",
          "Sword.png": "/assets/images/weapons/icons/Sword.png",
          "Cannon.png": "/assets/images/weapons/icons/Cannon.png",
          "Axe.png": "/assets/images/weapons/icons/Axe.png",
          "RocketLance.png": "/assets/images/weapons/icons/RocketLance.png",
          "Hammer.png": "/assets/images/weapons/icons/Hammer.png",
          "Spear.png": "/assets/images/weapons/icons/Spear.png",
          "Unarmed.png": "/assets/images/weapons/icons/Unarmed.png",
          "Fists.png": "/assets/images/weapons/icons/Fists.png"
        }
      },
      "errors": {
        "error-500.png": "/assets/images/errors/error-500.png",
        "error-404.png": "/assets/images/errors/error-404.png"
      },
      "og": {
        "main-og.jpg": "/assets/images/og/main-og.jpg"
      },
      "games": {
        "cupcakes": {
          "grandma.svg": "/assets/images/games/cupcakes/grandma.svg",
          "celestial.svg": "/assets/images/games/cupcakes/celestial.svg",
          "ivaldi.svg": "/assets/images/games/cupcakes/ivaldi.svg",
          "orion.svg": "/assets/images/games/cupcakes/orion.svg",
          "scarlet.svg": "/assets/images/games/cupcakes/scarlet.svg",
          "grimm.svg": "/assets/images/games/cupcakes/grimm.svg",
          "cupcake.svg": "/assets/images/games/cupcakes/cupcake.svg",
          "helpers.svg": "/assets/images/games/cupcakes/helpers.svg",
          "kitchen.svg": "/assets/images/games/cupcakes/kitchen.svg",
          "farms.svg": "/assets/images/games/cupcakes/farms.svg"
        }
      }
    }
  }
} as const;
