/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TreeImport } from './routes/tree'
import { Route as FoodScannerImport } from './routes/food-scanner'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TreeRoute = TreeImport.update({
  path: '/tree',
  getParentRoute: () => rootRoute,
} as any)

const FoodScannerRoute = FoodScannerImport.update({
  path: '/food-scanner',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/food-scanner': {
      id: '/food-scanner'
      path: '/food-scanner'
      fullPath: '/food-scanner'
      preLoaderRoute: typeof FoodScannerImport
      parentRoute: typeof rootRoute
    }
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/food-scanner': typeof FoodScannerRoute
  '/tree': typeof TreeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/food-scanner': typeof FoodScannerRoute
  '/tree': typeof TreeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/food-scanner': typeof FoodScannerRoute
  '/tree': typeof TreeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/food-scanner' | '/tree'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/food-scanner' | '/tree'
  id: '__root__' | '/' | '/food-scanner' | '/tree'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoodScannerRoute: typeof FoodScannerRoute
  TreeRoute: typeof TreeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoodScannerRoute: FoodScannerRoute,
  TreeRoute: TreeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/food-scanner",
        "/tree"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/food-scanner": {
      "filePath": "food-scanner.tsx"
    },
    "/tree": {
      "filePath": "tree.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
