name: Code QA
on: [push]
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Check
            action: vp run check
          # TODO: incrementally add these checks back
          # - name: Build
          #   action: vp run build
          - name: Health
            action: vp run health
    steps:
      - uses: actions/checkout@v6

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true
          sfw: true
          run-install: |
            - args: ['--frozen-lockfile']

      - name: ${{ matrix.name }}
        run: ${{ matrix.action }}
