name: Code QA
on: [push]
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Lint
            action: vp run check:lint
          - name: Format
            action: vp run check:format
          # TODO: incrementally add these checks back
          # - name: Typecheck
          #   action: vp run check:types
          # - name: Build
          #   action: vp run build
          - name: Dead Code
            action: vp run check:deadcode
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: corepack enable
      - run: vp install --frozen-lockfile
      - name: ${{ matrix.name }}
        run: ${{ matrix.action }}
